baseurl      = "localhost"
title        = "SabriUmut.com"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  # Subtitle for home
  homeSubtitle = "// iOS Developer //"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = ["/img/avatar.svg"]
  image = "/img/avatar.svg"

[taxonomies]
  tag      = "tags"
  category = "categories"

[languages]
  [languages.en]
    title = "Sabri Umut Sönmez"
    subtitle = "iOS Developer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    
    [languages.en.params.portrait]
        path = "/img/avatar.svg"
        alt = "My avatar"

    [languages.en.params.logo]
      logoText = "SabriUmut.com"
      logoHomeLink = "/"
      
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/sabrisonmez/"
    [[params.social]]
        name = "github"
        url = "https://github.com/sabrisonmez54"
    [[params.social]]
        name = "email"
        url = "mailto:ssonmez@tripshot.com?subject=Hi"
    
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about"
 [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "https://represent.io/sabrisonmez"
